collections:
  comic:
    output: true
    layout: "comic"

defaults:
  - scope:
      path: ""
    values:
      layout: "default"
      neko: "true"
  - scope:
      path: ""
      type: "comic"
    values:
      layout: "comic"

url: https://abslimeware.neocities.org
